spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: dummy-service
              uri: lb://DUMMY-SERVICE
              predicates:
                - Path=/api/dummy/**
              filters:
                - RewritePath=/api/dummy/(?<segment>.*), /api/${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "banking-demo-jwt-secret-key-must-be-at-least-32-bytes-long"
    access-token-ttl: 15m
    refresh-token-ttl: 7d
