server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    consumer:
      group-id: account-service-group
      properties:
        spring.json.trusted.packages: "*"
