server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/accounts/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**
            - id: dummy-service
              uri: lb://DUMMY-SERVICE
              predicates:
                - Path=/api/dummy/**
              filters:
                - RewritePath=/api/dummy/(?<segment>.*), /api/${segment}
