server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    consumer:
      group-id: notification-service-group
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  notification:
    mail:
      from: noreply@banking.local
      enabled: true
